
trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_Docker_Image_Stage
    displayName: Build_Docker_Image_Stage
    jobs:
      - job: Build_docker_Image_Job
        displayName: Build_Docker_Image_Job
        steps:
          
          - task: Docker@2
            inputs:
              containerRegistry: 'acrjan06-devops-svc'
              repository: 'apr24repo'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
